services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: evaluer_db
      POSTGRES_USER: evaluer
      POSTGRES_PASSWORD: evaluer
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U evaluer"]
      interval: 10s
      timeout: 5s
      retries: 5

  evaluer-api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn evaluer.app:app --host 0.0.0.0 --port 8000 --reload
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
