"""Add parent_id to grades

Revision ID: 627c17e201b3
Revises: d7cee5c1be2c
Create Date: 2025-08-02 22:00:29.379558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '627c17e201b3'
down_revision: Union[str, Sequence[str], None] = 'd7cee5c1be2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_grades', sa.Column('module_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_assignment_grades_module_id'), 'assignment_grades', ['module_id'], unique=False)
    op.add_column('module_grades', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_module_grades_subject_id'), 'module_grades', ['subject_id'], unique=False)
    op.add_column('response_grades', sa.Column('assignment_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_response_grades_assignment_id'), 'response_grades', ['assignment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_grades_assignment_id'), table_name='response_grades')
    op.drop_column('response_grades', 'assignment_id')
    op.drop_index(op.f('ix_module_grades_subject_id'), table_name='module_grades')
    op.drop_column('module_grades', 'subject_id')
    op.drop_index(op.f('ix_assignment_grades_module_id'), table_name='assignment_grades')
    op.drop_column('assignment_grades', 'module_id')
    # ### end Alembic commands ###
