"""Add unique constraint to response_grades

Revision ID: d7cee5c1be2c
Revises: 
Create Date: 2025-08-02 21:05:18.487771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7cee5c1be2c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignment_grades_id'), table_name='assignment_grades')
    op.drop_index(op.f('ix_assignment_grades_student_id'), table_name='assignment_grades')
    op.create_index(op.f('ix_assignment_grades_student_id'), 'assignment_grades', ['student_id'], unique=False)
    op.create_unique_constraint('uq_assignment_grades_assignment_student', 'assignment_grades', ['assignment_id', 'student_id'])
    op.drop_index(op.f('ix_module_grades_id'), table_name='module_grades')
    op.drop_index(op.f('ix_module_grades_student_id'), table_name='module_grades')
    op.create_index(op.f('ix_module_grades_student_id'), 'module_grades', ['student_id'], unique=False)
    op.create_unique_constraint('uq_module_grades_module_student', 'module_grades', ['module_id', 'student_id'])
    op.drop_index(op.f('ix_overall_grades_id'), table_name='overall_grades')
    op.drop_index(op.f('ix_overall_grades_student_id'), table_name='overall_grades')
    op.create_index(op.f('ix_overall_grades_student_id'), 'overall_grades', ['student_id'], unique=False)
    op.create_unique_constraint('uq_overall_grades_student', 'overall_grades', ['student_id'])
    op.drop_index(op.f('ix_response_grades_id'), table_name='response_grades')
    op.drop_index(op.f('ix_response_grades_student_id'), table_name='response_grades')
    op.create_index(op.f('ix_response_grades_student_id'), 'response_grades', ['student_id'], unique=False)
    op.create_unique_constraint('uq_response_grades_response_student', 'response_grades', ['response_id', 'student_id'])
    op.drop_index(op.f('ix_subject_grades_id'), table_name='subject_grades')
    op.drop_index(op.f('ix_subject_grades_student_id'), table_name='subject_grades')
    op.create_index(op.f('ix_subject_grades_student_id'), 'subject_grades', ['student_id'], unique=False)
    op.create_unique_constraint('uq_subject_grades_subject_student', 'subject_grades', ['subject_id', 'student_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_subject_grades_subject_student', 'subject_grades', type_='unique')
    op.drop_index(op.f('ix_subject_grades_student_id'), table_name='subject_grades')
    op.create_index(op.f('ix_subject_grades_student_id'), 'subject_grades', ['student_id'], unique=True)
    op.create_index(op.f('ix_subject_grades_id'), 'subject_grades', ['id'], unique=False)
    op.drop_constraint('uq_response_grades_response_student', 'response_grades', type_='unique')
    op.drop_index(op.f('ix_response_grades_student_id'), table_name='response_grades')
    op.create_index(op.f('ix_response_grades_student_id'), 'response_grades', ['student_id'], unique=True)
    op.create_index(op.f('ix_response_grades_id'), 'response_grades', ['id'], unique=False)
    op.drop_constraint('uq_overall_grades_student', 'overall_grades', type_='unique')
    op.drop_index(op.f('ix_overall_grades_student_id'), table_name='overall_grades')
    op.create_index(op.f('ix_overall_grades_student_id'), 'overall_grades', ['student_id'], unique=True)
    op.create_index(op.f('ix_overall_grades_id'), 'overall_grades', ['id'], unique=False)
    op.drop_constraint('uq_module_grades_module_student', 'module_grades', type_='unique')
    op.drop_index(op.f('ix_module_grades_student_id'), table_name='module_grades')
    op.create_index(op.f('ix_module_grades_student_id'), 'module_grades', ['student_id'], unique=True)
    op.create_index(op.f('ix_module_grades_id'), 'module_grades', ['id'], unique=False)
    op.drop_constraint('uq_assignment_grades_assignment_student', 'assignment_grades', type_='unique')
    op.drop_index(op.f('ix_assignment_grades_student_id'), table_name='assignment_grades')
    op.create_index(op.f('ix_assignment_grades_student_id'), 'assignment_grades', ['student_id'], unique=True)
    op.create_index(op.f('ix_assignment_grades_id'), 'assignment_grades', ['id'], unique=False)
    # ### end Alembic commands ###
